/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_CONSTANTS_H
#define user_CONSTANTS_H

#include "user_types.h"



class userConstants {
 public:
  userConstants();

};

extern const userConstants g_user_constants;



#endif
